# Generated by Django 5.1.2 on 2024-11-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmiRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20)),
                ('top_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bottom_bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('breakfast', models.TextField(blank=True, help_text='Breakfast meal recommendation.', null=True)),
                ('lunch', models.TextField(blank=True, help_text='Lunch meal recommendation.', null=True)),
                ('dinner', models.TextField(blank=True, help_text='Dinner meal recommendation.', null=True)),
                ('snacks', models.TextField(blank=True, help_text='Snack options for this meal plan.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bmi_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplans.bmirange')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplans.mealplan')),
            ],
        ),
    ]
