# Generated by Django 5.1.2 on 2024-11-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0002_bmirange_mealplan_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirange',
            name='is_less_then_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bmirange',
            name='is_more_then_bottom',
            field=models.BooleanField(default=False),
        ),
    ]
