# Generated by Django 5.1.2 on 2024-12-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0007_mealcategory_alter_meal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/meal_category/'),
        ),
    ]
