# Generated by Django 5.1.2 on 2024-12-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0008_mealcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/meals/'),
        ),
    ]
