# Generated by Django 5.1.2 on 2024-12-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0009_alter_meal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefineddailymeal',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='predefineddailymeal',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='predefineddailymeal',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='predefineddailymeal',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='predefinedmealplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='predefineddailymeal',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealCategory',
        ),
        migrations.DeleteModel(
            name='PredefinedDailyMeal',
        ),
        migrations.DeleteModel(
            name='PredefinedMealPlan',
        ),
    ]
