# Generated by Django 5.1.2 on 2024-12-23 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0010_remove_predefineddailymeal_lunch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='bmi_range',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='MealPlan',
        ),
    ]
