# Generated by Django 5.1.2 on 2024-12-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0011_remove_mealplan_bmi_range_delete_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3'), (4, 'Day 4'), (5, 'Day 5'), (6, 'Day 6'), (7, 'Day 7'), (8, 'Day 8'), (9, 'Day 9'), (10, 'Day 10'), (11, 'Day 11'), (12, 'Day 12'), (13, 'Day 13'), (14, 'Day 14'), (15, 'Day 15'), (16, 'Day 16'), (17, 'Day 17'), (18, 'Day 18'), (19, 'Day 19'), (20, 'Day 20'), (21, 'Day 21'), (22, 'Day 22'), (23, 'Day 23'), (24, 'Day 24'), (25, 'Day 25'), (26, 'Day 26'), (27, 'Day 27'), (28, 'Day 28'), (29, 'Day 29'), (30, 'Day 30')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plan/meal/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plan/meal/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('total_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('header_text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plan/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_popular', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plan/meal/')),
                ('food_list', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplans.dailyplan')),
            ],
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='mealplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meals', to='mealplans.mealplan'),
        ),
        migrations.CreateModel(
            name='MealPlanDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/plan/meal/description/')),
                ('description', models.TextField(blank=True, null=True)),
                ('list_item', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_descriptions', to='mealplans.mealplan')),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='mealplans.plan'),
        ),
    ]
