# Generated by Django 5.1.2 on 2024-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0012_dailyplan_mealplan_plan_meal_dailyplan_mealplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
