# Generated by Django 5.1.2 on 2024-12-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0015_remove_meal_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='health_level',
            field=models.CharField(blank=True, choices=[('Under Weight', 'Under Weight'), ('Balanced', 'Balanced'), ('Over Weight', 'Overweight'), ('Obesity', 'Obesity')], max_length=30, null=True),
        ),
    ]
