# Generated by Django 5.1.2 on 2024-12-23 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0016_mealplan_health_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegisteredPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current_plan', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplans.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mealplans.mealplan')),
            ],
        ),
    ]
