# Generated by Django 5.1.2 on 2024-12-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplans', '0018_customerregisteredplan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='health_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Under Weight'), (2, 'Balanced'), (3, 'Over Weight'), (4, 'Obesity')], null=True),
        ),
    ]
